### ISSUE TITLE
Missing Images/Resources

### ISSUE THREAD

**Issue by westonwatson** [sizeofcat/civitas#1]
Following the only directions I could see in the `README.md` - Everything else seems to be fine/working, except all the images are missing.
> I'm very interested in playing/testing the game. Let me know if I missed a step or if there's something I can help with in order to get this working on my machine (Macbook). It appears that the `assets` sub-directory is missing from the `images` folder.

Steps taken:

1. $ docker build -t civitas .
2. $ docker run --name civitas-dev -d -p 10082:80 civitas
3. Opened Browser to http://localhost:10082.

Screenshot(s): 
![screenshot1](https://i.imgur.com/VEz4lnO.png)
![screenshot2](https://i.imgur.com/gLYY6LJ.png)

**Comment by sizeofcat** [comment]
Hey @westonwatson,

You can download the Bluebyte assets from [here](http://s000.tinyupload.com/index.php?file_id=06626343760914911767). Unzip the archive inside the images directory and let me know if everything is ok.

Take care!
