### ISSUE TITLE
Almost no images in game

### ISSUE THREAD

**Issue by Areso** [sizeofcat/civitas#31]
Google Chrome 60.0.3112.101 (official build), (64 bit)
as well Mozilla Firefox 54.0.X 32 bit
Windows 8.1 64 bit
![issue2-almost-no-pictures](https://user-images.githubusercontent.com/4927300/29507650-de6f3d42-8672-11e7-92bf-e5b96cb18db3.png)

**Comment by Areso** [comment]
0.2 (April 30, 2017) - doesn't have this problem, only download repo has this problem.

**Comment by Areso** [comment]
0.2 looks like this.
![issue2-almost-no-pictures](https://user-images.githubusercontent.com/4927300/29508036-be25f6f0-8674-11e7-83a6-d4c223771243.png)

**Comment by sizeofcat** [comment]
The missing images are copyrighted by BlueByte software so I cannot redistribute them, the images currently in game are custom made and can be distributed.

A copy of the copyrighted images can be found [here](https://transfer.sh/r1lwX/civitas-assets.zip), but of course, distribution is prohibited. Just use them for testing (copy the assets folder inside the zip file into your `images` Civitas directory.

**Comment by Benchwork** [comment]
file not found. anyone else have a link?

**Comment by Areso** [comment]
I didn't download it. I interested mostly in code and in ideas.

**Comment by sizeofcat** [comment]
@Benchwork https://transfer.sh/tJhbx/civitas-assets.zip

**Comment by Benchwork** [comment]
@sizeofcat thank you

**Comment by deltianomegian** [comment]
Not found?

**Comment by deltianomegian** [comment]
Could you please post a usable link @sizeofcat

**Comment by sizeofcat** [comment]
Hey @deltianomegian, I've uploaded the assets https://transfer.sh/YV0vf/civitas-assets.zip
Let me know if everything works as expected (copy the assets directory from the archive to your Civitas' images directory as instructed above).

**Comment by devangkantharia** [comment]
Hi! great work. I am facing the same issue. The assets are not available on any of the links mentioned. 
1) https://transfer.sh/r1lwX/civitas-assets.zip
2) https://transfer.sh/tJhbx/civitas-assets.zip
3) https://transfer.sh/YV0vf/civitas-assets.zip
Could you please reupload the new asset folder, I want to test the game ASAP.
I can also contribute in recreating free assets.

**Comment by sizeofcat** [comment]
Hey @devangkantharia, thank you. Here is an updated link to the game assets.

http://s000.tinyupload.com/index.php?file_id=04671461179640679005

Make sure you copy the **assets** directory inside the zip file into your **images** Civitas directory.
Take care.
