### ISSUE TITLE
Assets missing

### ISSUE THREAD

**Issue by rui-ribeiro** [sizeofcat/civitas#32]
HI!

I think you have a very interesting project here, congrats.

I cloned the repo but is missing some assets I think, I could find some of them in v2.0 tag but the folder resources I coulnd't find it.

I'm missing something?

Thanks in advance

**Comment by sizeofcat** [comment]
Hey Rui,

Thank you!

Check out [this issue](https://github.com/sizeofcat/civitas/issues/31) regarding the missing assets, I'll make a note in the readme file and link to the issue.

**Comment by rui-ribeiro** [comment]
Thanks!
