### ISSUE TITLE
What happened to the Assets?

### ISSUE THREAD

**Issue by deltianomegian** [sizeofcat/civitas#36]
All the links link to a text document that reads: 'Not Found'
Could someone please post the link or file of the assets in civitas

**Comment by sizeofcat** [comment]
Check out [this issue](https://github.com/sizeofcat/civitas/issues/31#issuecomment-394681577).

**Comment by deltianomegian** [comment]
Thanks so much @sizeofcat... I look forward to seeing your next projects!  😄
